# Generated by Django 5.1.6 on 2025-05-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=5000)),
                ('Gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=5)),
                ('Mobile', models.IntegerField()),
                ('Address', models.CharField(max_length=500000)),
            ],
        ),
    ]
